import assert from "node:assert/strict";
import fs from "node:fs";

const setup = fs.readFileSync("web/app/forge/forge.js", "utf8");
const session = fs.readFileSync("web/app/forge/bindery.js", "utf8");
const workings = fs.readFileSync("web/app/forge/workings.js", "utf8");
const menu = fs.readFileSync("web/app/ui/menu.js", "utf8");
const traceLines = fs.readFileSync("web/app/forge/trace-lines.js", "utf8");
const binder = fs.readFileSync("web/app/forge/binder.js", "utf8");
const baseCss = fs.readFileSync("web/css/overlay/bindery/base.css", "utf8");
const binderyCss = fs.readFileSync("web/css/overlay/bindery.css", "utf8");
const priorKnowledgeCss = fs.readFileSync("web/css/overlay/bindery/prior-knowledge.css", "utf8");
const authorRouteCss = fs.readFileSync("web/css/overlay/bindery/author-route.css", "utf8");
const resetCss = fs.readFileSync("web/css/overlay/bindery/binder-reset.css", "utf8");
const sessionCss = fs.readFileSync("web/css/overlay/bindery/session.css", "utf8");
const launcher = fs.readFileSync("start.sh", "utf8");
const main = fs.readFileSync("web/app/main.js", "utf8");
const routesGet = fs.readFileSync("arcanum/routes_get.py", "utf8");
const { fallbackCourseControl, formatCourseBlockers } = await import("../../../web/app/forge/course-control.js");
const phaseMatch = session.match(/export const FORGE_PHASES = \[([\s\S]*?)\];/);
assert.ok(phaseMatch);
assert.equal((phaseMatch[1].match(/"[^"]+"/g) || []).length, 8);
assert.match(setup, /PHASE AUTHORS/);
assert.match(setup, /PHASES 1–2[\s\S]*ARC \+ SKELETON/);
assert.match(setup, /PHASES 3–7[\s\S]*BUILD \+ VALIDATE/);
assert.match(setup, /PHASE 8[\s\S]*STUDENT REVIEW/);
assert.match(setup, /Start 1 uses low-density lessons[\s\S]*Start 2 uses moderate density[\s\S]*Start 3 permits dense related material/);
const priorLevelMatch = setup.match(/const PRIOR_KNOWLEDGE_LEVELS = \{([\s\S]*?)\n\};/);
assert.ok(priorLevelMatch);
assert.equal((priorLevelMatch[1].match(/^\s+\d+:\s*\[/gm) || []).length, 10);
assert.match(priorLevelMatch[1], /1: \["FROM ZERO", "Nothing is skipped/);
assert.match(priorLevelMatch[1], /4: \["TRANSFER LEARNER", "General programming ideas/);
assert.match(priorLevelMatch[1], /10: \["EXPERT", "Only relevant non-obvious/);
assert.match(setup, /id="fg-prior-level"[^>]*aria-describedby="fg-prior-level-summary"/);
assert.match(setup, /id="fg-prior-level-summary" aria-live="polite" aria-atomic="true"/);
assert.match(setup, /Entrance pacing changes; Language Mastery still owns the exit skills and final evidence/);
assert.match(setup, /aria-label="Author agent CLI"/);
assert.match(setup, /aria-label="Author model"/);
assert.match(setup, /aria-label="Author effort"/);
assert.match(setup, /aria-label="Phases 3 through 7 author agent CLI"/);
assert.match(setup, /aria-label="Phases 3 through 7 author model"/);
assert.match(setup, /VALIDATOR AI[\s\S]*MANDATORY · AFTER EVERY SECTION/);
assert.match(setup, /aria-label="Validator AI agent CLI"/);
assert.match(setup, /aria-label="Validator AI model"/);
assert.match(setup, /About Validator AI[\s\S]*prerequisite completeness/);
assert.match(setup, /gpt-5\.6-luna/);
assert.match(setup, /Responses API/);
assert.doesNotMatch(setup, /service_tier[\s\S]*flex/i);
assert.match(setup, /aria-label="Phase 8 author agent CLI"/);
assert.match(setup, /aria-label="Phase 8 author model"/);
assert.match(setup, /THOROUGH REVIEWER AI/);
assert.match(setup, /reads every authored[\s\S]*no sampling/i);
assert.match(setup, /aria-label="About thorough reviewer AI"/);
assert.doesNotMatch(setup, /class="forge-reviewer-copy"/);
assert.match(setup, /forge-reviewer-field[\s\S]*forge-reviewer-head[\s\S]*THOROUGH REVIEWER AI[\s\S]*About thorough reviewer AI[\s\S]*forge-reviewer-toggle[\s\S]*fg-review-enabled[\s\S]*ENABLE \(OPTIONAL\)/);
assert.doesNotMatch(setup, /SECTION SEMANTIC REVIEW|semanticReview|fg-sem-|binderySemanticReview/);
assert.equal(fs.existsSync("tools/buildlib/semantic_review.py"), false);
assert.match(setup, /aria-label="Reviewer agent CLI"/);
assert.match(setup, /author, authors, validator, reviewer, bindery: \{ author, authors, validator, reviewer \}/);
assert.match(setup, /localStorage\.setItem\("binderyValidator", JSON\.stringify\(validator\)\)/);
assert.match(setup, /localStorage\.setItem\("binderyAuthors", JSON\.stringify\(authors\)\)/);
assert.match(setup, /RESUME FROM CURRENT/);
assert.match(setup, /RESTART FROM PHASE/);
assert.match(setup, /id="fg-resume-ack"/);
assert.doesNotMatch(setup, /fg-resume-note|resets learner progress|all learner progress will be erased/);
assert.match(setup, /I understand this erases authored work from the selected phase onward\./);
assert.match(setup, /confirm: "reset-tome-build"/);
assert.match(setup, /fromPhase: restartPhase/);
assert.match(setup, /\/api\/buildtome\/reset/);
assert.match(workings, /aria-label="Delete draft tome"[\s\S]*ico\("x"\)/);
assert.doesNotMatch(workings, /🗑|resume-trash/);
assert.match(workings, /DELETE THIS DRAFT TOME\?[\s\S]*Are you sure\?/);
assert.match(workings, /confirm: "discard-draft", confirmWorking: working\.id/);
assert.doesNotMatch(setup, /THE DRAFTER|THE REVIEWER|quality|advised/);
assert.match(setup, /id="fg-project-scope" type="range" min="1" max="5"/);
assert.match(setup, /MINIMAL PROOF[\s\S]*FULL-FLEDGED PROJECT/);
assert.doesNotMatch(setup, /test game|playable prototype|short game|feature-rich game|feasible game/i);
assert.match(setup, /id="fg-project-scope-summary" aria-live="polite"/);
assert.match(setup, /project_scope: \$\("#fg-project-scope"/);
assert.doesNotMatch(setup, /id="fg-breadth"|breadth: \$\("#fg-breadth"/);
assert.match(setup, /MASTERY_DEPTH_FLOORS/);
assert.match(session, /AUTHOR TOOL HISTORY/);
assert.match(session, /OBLIGATIONS OPEN/);
assert.match(session, /DUE NOW/);
assert.doesNotMatch(session, /VALIDATOR AI/);
assert.doesNotMatch(session, /validator\.callCount|API \$\{validator\.apiCalls\}/);
assert.match(session, /paintCourseControl\(overlay, status\.courseControl, tooling\?\.usage\)/);
assert.match(session, /usage\.freshInputTokens[\s\S]*usage\.cachedInputTokens[\s\S]*usage\.cacheWriteTokens[\s\S]*usage\.outputTokens/);
assert.match(session, /id="tome-forge" disabled aria-busy="true"/);
assert.match(session, /fetchActiveBuilds\(\{ failClosed: true \}\)/);
assert.match(session, /forgeButton\.disabled = busy/);
assert.match(session, /setTimeout\(refreshActiveBuilds, 3000\)/);
assert.match(session, /Finish or abandon the current working/);
assert.match(session, /fetch\(`\/api\/buildtome\/status\?id=/);
assert.match(session, /data-trace="\$\{esc\(build\.traceId \|\| build\.id\)\}"/);
assert.match(session, /openBuildOverlay\(button\.dataset\.job, button\.dataset\.trace\)/);
assert.match(session, /\/api\/buildtome\/pause/);
assert.match(session, /\/api\/buildtome\/message/);
assert.match(session, /\/api\/buildtome\/continue/);
assert.match(session, /forge-fail-controls[\s\S]*forge-ai-row[\s\S]*id="fp-alt-resume"/);
assert.match(session, /class="forge-console-btn" id="fp-alt-resume"/);
assert.doesNotMatch(session, /class="forge-console-btn primary" id="fp-alt-resume"/);
assert.match(session, /mergeForgeTraceLines\(tooling\?\.lines, status\.logtail, traceAnchor\)/);
assert.match(traceLines, /VALIDATOR COMMAND\|AI VALIDATOR CALL/);
assert.match(traceLines, /rows\.sort/);
assert.match(session, /class="forge-chat-text"/);
assert.match(session, /function messageStamp\(value\)/);
assert.doesNotMatch(session, /function commandStamp\(line\)/);
assert.doesNotMatch(session, /forge-terminal-time|forge-terminal-command/);
assert.match(session, /<div class="forge-terminal-line">\$\{esc\(line\)\}<\/div>/);
assert.match(session, /<time datetime=/);
assert.match(session, /forge-console-actions[\s\S]*id="fp-pause"[\s\S]*id="fp-send"/);
assert.doesNotMatch(session, /forge-session-actions[\s\S]{0,300}id="fp-pause"/);
assert.match(session, /pauseTransition === "pause" \? "pausing"/);
assert.match(session, /pause\.disabled = state === "pausing" \|\| state === "resuming"/);
assert.doesNotMatch(session, /setTimeout\(\(\) => \{ pause\.disabled = false/);
assert.match(session, /phaseLine\(status, state\)/);
assert.match(session, /active && status\.activityStartedAt/);
assert.doesNotMatch(session, /Date\.now\(\) \/ 1000 - status\.phaseStartedAt/);
assert.match(session, /phase\.dataset\.state = state/);
assert.match(session, /retainedTooling/);
assert.match(fs.readFileSync("tools/buildlib/single_author/__init__.py", "utf8"), /self\.state\("starting", pid=self\.child\.pid\)/);
assert.match(session, /id="fp-model">ATTACHING/);
assert.match(session, /status\.sessionAuthor \|\| \{\}/);
assert.match(routesGet, /session\.get\("actualModel"\) or session\.get\("model"\)/);
assert.match(routesGet, /"requestedModel": session\.get\("model"\)/);
assert.match(session, /author\.model/);
assert.match(baseCss, /#fp-phase\[data-state="pausing"\]/);
assert.match(baseCss, /#fp-phase\[data-state="validating"\]/);
assert.match(baseCss, /\.tome-row\.forging\[data-state="validating"\] \.jr-desc/);
assert.match(baseCss, /\.forge-depth input\[type="range"\]\s*\{[^}]*min-width:\s*0/s);
assert.match(binderyCss, /base\.css"\);\s*@import url\("\.\/bindery\/prior-knowledge\.css"\);/s);
assert.match(priorKnowledgeCss, /\.forge-prior-summary\s*\{[^}]*grid-template-columns:[^}]*min-block-size:\s*58px/s);
assert.match(sessionCss, /\.forge-dials \.forge-field,[\s\S]*?\.forge-dials \.forge-depth\s*\{[^}]*min-width:\s*0/s);
assert.match(authorRouteCss, /\.forge-ai-row\s*\{[^}]*display:\s*grid[^}]*grid-template-columns:/s);
assert.match(sessionCss, /\.tome-row\.forge:disabled\s*\{[^}]*filter:\s*grayscale\(\.82\)[^}]*opacity:\s*\.56/s);
assert.match(authorRouteCss, /\.forge-author-field\s*\{[^}]*padding:[^}]*border:/s);
assert.match(authorRouteCss, /\.forge-reviewer-field\s*\{[^}]*border:[^}]*background:/s);
assert.match(authorRouteCss, /\.forge-reviewer-options\s*\{[^}]*margin-top:\s*2px/s);
assert.doesNotMatch(authorRouteCss, /\.forge-reviewer-options\s*\{[^}]*margin-left:/s);
assert.doesNotMatch(sessionCss, /\.forge-terminal-line\s*\{[^}]*grid-template-columns:/s);
assert.match(sessionCss, /\.forge-dial-summary\s*\{[^}]*block-size:\s*92px[^}]*overflow-y:\s*auto[^}]*scrollbar-gutter:\s*stable/s);
assert.match(sessionCss, /\.forge-resume-field\s*\{[^}]*border:[^}]*background:/s);
assert.match(sessionCss, /\.forge-field \.forge-resume-ack\s*\{[^}]*color:\s*var\(--bad\)/s);
assert.match(sessionCss, /\.forge-field \.forge-resume-ack\s*\{[^}]*align-items:\s*center/s);
assert.match(sessionCss, /\.forge-session-model strong\s*\{[^}]*color:\s*var\(--ac\)/s);
assert.match(sessionCss, /\.forge-composer textarea\s*\{[^}]*resize:\s*none/s);
assert.match(sessionCss, /--forge-body-size:\s*12\.5px/);
assert.match(sessionCss, /--forge-meta-size:\s*9\.5px/);
assert.match(sessionCss, /\.forge-composer textarea\s*\{[^}]*font:\s*var\(--forge-body-size\)[^}]*var\(--fell\)/s);
assert.match(sessionCss, /\.forge-composer textarea::placeholder\s*\{[^}]*font:\s*inherit/s);
assert.match(sessionCss, /\.forge-chat-text\s*\{[^}]*white-space:\s*pre-wrap/s);
assert.match(sessionCss, /\.forge-chat-meta\s*\{[^}]*justify-content:\s*space-between/s);
assert.doesNotMatch(sessionCss, /\.forge-chat\s*\{[^}]*white-space:\s*pre-wrap/s);
assert.match(sessionCss, /\.forge-console-btn\s*\{[^}]*background:[^}]*color:/s);
assert.match(sessionCss, /\.forge-console-btn\s*\{[^}]*min-height:\s*26px[^}]*font:\s*10\.5px/s);
assert.match(sessionCss, /\.forge-fail-controls\s*\{[^}]*grid-template-columns:\s*minmax\(0, 1fr\) auto/s);
assert.match(sessionCss, /\.forge-fail-controls \.dd-btn\s*\{[^}]*box-sizing:\s*border-box/s);
assert.match(menu, /parentElement\?\.classList\.contains\("dd"\)/);
const resetOptions = binder.match(/<select id="bd-phase"[\s\S]*?<\/select>/)?.[0] || "";
assert.equal((resetOptions.match(/<option value="[1-8]">/g) || []).length, 8);
assert.match(binder, /Every authored section is replaced by fresh Phase 3 placeholders/);
assert.match(session, /fallbackCourseControl/);
assert.match(session, /STATUS FALLBACK/);
assert.match(routesGet, /courseControlError/);
const fallback = fallbackCourseControl({ sections: [
  { id: "s01", title: "First", build: "Build the first slice." },
  { id: "s02", title: "Second", build: "Build the second slice." },
] }, { sectionProgress: { section: "s02", index: 2, total: 2 } });
assert.equal(fallback.currentSection, "s02");
assert.deepEqual(fallback.spine.map((row) => [row.id, row.status, row.mark]), [
  ["s01", "verified", "✓"], ["s02", "current", "▶"],
]);
assert.equal(formatCourseBlockers(["s01-retire-s02-01 is due now"]),
  "DUE NOW · s01-retire-s02-01");
assert.equal(formatCourseBlockers(["s01-retire-s02-01 is due now", "s02: proof failed"]),
  "DUE NOW · s01-retire-s02-01 · BLOCKED · s02: proof failed");
assert.match(binder, /prepareStateReset\(\)/);
assert.match(binder, /confirm: "reset-tome-build"/);
assert.match(binder, /\/api\/buildtome\/reset/);
assert.match(binder, /\/api\/buildtome\/resume/);
assert.match(resetCss, /\.binder-rebuild-consequence\s*\{[^}]*border-left:\s*2px solid var\(--bad\)/s);
assert.match(main, /openResetBuildJob/);
assert.match(main, /openBuildOverlay\(resetBuildJob\)/);
assert.match(launcher, /\/api\/buildtome\/active/);
assert.match(launcher, /active author session/);
assert.match(launcher, /if \[\[ "\$active_jobs" =~ \^\[1-9\]/);
assert.match(launcher, /open_arcanum\(\)/);
assert.match(launcher, /ARCANUM_NO_OPEN/);
assert.match(launcher, /open_arcanum\s*\n\s*exit 0/);
assert.match(main, /#term, \.forge-log, \.forge-workbench/);
console.log("single-author forge UI: OK");
