#!/usr/bin/env python3
"""Install or remove the disposable tome used by the real-browser mastery journey."""
from __future__ import annotations

import argparse
import json
from pathlib import Path
import shutil
import sys
import tempfile


ROOT = Path(__file__).resolve().parents[3]
sys.path[:0] = [str(ROOT), str(ROOT / "tools")]

from buildlib.mastery_evidence import export_mastery_contract
from buildlib.mastery_evidence.variants import VariantGenerator
from runtimes import for_config
from tools.tests.mastery.authoring.fixture import (
    PythonProofSandbox, SemanticPass, write_labs, write_working_assessments,
)
from tools.tests.mastery.fixtures import future_map


TOME_ID = "mastery-browser-fixture"
TARGET = ROOT / "tomes" / TOME_ID
LEGACY_TOME_ID = "legacy-browser-fixture"
LEGACY_TARGET = ROOT / "tomes" / LEGACY_TOME_ID
MARKER = ".arcanum-browser-fixture"
PROJECT = "BrowserEvidence"


def _remove() -> None:
    targets = [target for target in (TARGET, LEGACY_TARGET) if target.exists()]
    for target in targets:
        if not (target / MARKER).is_file():
            raise RuntimeError(f"refusing to remove unmarked directory: {target}")
    for target in targets:
        shutil.rmtree(target)


def _manifest(root: Path) -> None:
    sections = [f"s{ordinal:02d}" for ordinal in range(1, 10)]
    (root / "tome.toml").write_text(f'''# Disposable browser integration fixture. Generated by {Path(__file__).name}.
[meta]
id = "{TOME_ID}"
name = "Mastery Evidence Browser Journey"
description = "A disposable end-to-end fixture for the evidence learner journey."
author = "The Arcanum test harness"
version = "1.0.0"
favicon = "✦"

[mastery]
evidenceVersion = 1
level = 2

[runtime]
name = "python"
project = "{PROJECT}"
packages = false

[content]
sections = {json.dumps(sections)}

[narrative]
objective = "Resolve required learning work, pass deterministic Workings, and demonstrate independent transfer in an isolated mastery lab."
title = "ARCANUM // MASTERY EVIDENCE JOURNEY"
logo = "EVIDENCE ENGINE"
opsLabel = "EVIDENCE CHAPTERS"
graderPersona = "THE EVIDENCE KEEPER"
studentTerm = "learner"
currency = "proof marks"
currencyShort = "pm"
gradeScale = "S|A|B|C|D|F"
bootLines = ["The evidence ledger opens."]
gradingLines = ["The deterministic checks are running."]
completeText = "THE PROJECT IS COMPLETE // Mastery remains a separate evidence claim."

[defaults]
theme = "vellum"

[economy]
ranks = [[0, "LEARNER"], [100, "EVIDENCE BEARER"]]
hintCost = 0
oracleCost = 0
attemptMultipliers = [1, 0.6, 0.3]
comboStep = 0.05
comboCap = 0.5
sRankMultiplier = 1.5
attackStakePerDiff = 20
attackWinPerDiff = 15
''', encoding="utf-8")


def _exercise_toml(sid: str, capability: str) -> str:
    exercise_id = f"{sid}-l01-e01"
    if sid not in {"s08", "s09"}:
        return f'''[[lessons.exercises]]
id = "{exercise_id}"
type = "type"
points = 10
reps = 1
prompt = "Recast the prior construction pattern."
code = "print(\\"READY\\")"
required = true
capabilities = ["{capability}"]
cognitiveTask = "build"
scaffold = "guided"
contextFamily = "context-{sid}"
aidPolicy = "learning"
'''
    label = "late chapter" if sid == "s08" else "final chapter"
    return f'''[[lessons.exercises]]
id = "{exercise_id}"
type = "mc"
points = 20
prompt = "Which result is required before the {label} Working can unlock?"
choices = ["Some required activities", "Every required activity", "Only optional enrichment"]
answer = 1
hint = "The evidence contract uses a complete required-work gate."
whyWrong = "Optional enrichment is excluded, but every required activity must resolve."
explain = "Every required activity must resolve before the Working unlocks."
required = true
capabilities = ["{capability}"]
cognitiveTask = "recall"
scaffold = "guided"
contextFamily = "context-{sid}"
aidPolicy = "learning"
reviewVariants = [{{ prompt = "What completion fraction unlocks an evidence Working?", choices = ["70%", "80%", "100% of required work"], answer = 2 }}]
'''


def _optional_toml(capability: str) -> str:
    return f'''\n[[lessons.exercises]]
id = "s08-l01-e02"
type = "mc"
points = 5
prompt = "Optional enrichment: which ledger label follows independent evidence?"
choices = ["Practiced", "Independently demonstrated", "Not started"]
answer = 1
required = false
capabilities = ["{capability}"]
cognitiveTask = "recognize"
scaffold = "guided"
contextFamily = "optional-s08"
aidPolicy = "learning"
'''


def _section_files(root: Path, contract: dict) -> None:
    for ordinal in range(1, 10):
        sid = f"s{ordinal:02d}"
        capability = contract["capabilityIds"][(ordinal - 1) % len(contract["capabilityIds"])]
        section_root = root / "sections" / sid
        lessons_root = section_root / "lessons"
        lessons_root.mkdir(parents=True)
        (section_root / "section.toml").write_text(f'''id = "{sid}"
codename = "CHAPTER {ordinal} // EVIDENCE"
short = "Evidence {ordinal}"
title = "Evidence Contract {ordinal}"
build = "Extend one cumulative Python program and prove the declared behavior."
brief = "This fixture isolates the learner-facing rules of the mastery evidence engine."
''', encoding="utf-8")
        optional = _optional_toml(capability) if sid == "s08" else ""
        (lessons_root / "l01.toml").write_text(f'''[[lessons]]
id = "{sid}-l01"
title = "Required and Optional Evidence"
body = """<p>Required learning work controls the Working gate. Optional enrichment never blocks it.</p>"""
teaches = ["{capability}"]

{_exercise_toml(sid, capability)}{optional}
''', encoding="utf-8")
        performance_ids = [
            row["id"] for row in contract["performances"]
            if row["nodeId"] == f"{sid}.working"
        ]
        (section_root / "freestyle.toml").write_text(f'''[freestyle]
title = "THE GREAT WORKING: {sid.upper()}"
brief = "Keep the cumulative program runnable and make it emit <code>READY</code>."
reward = 40
masteryPerformances = {json.dumps(performance_ids)}

[freestyle.badge]
id = "badge-{sid}"
name = "EVIDENCE {ordinal}"
desc = "The chapter's deterministic contract is green."

[[freestyle.requirements]]
id = "observable-result"
text = "The cumulative program builds and prints READY."
essential = true
capabilities = ["{capability}"]

[[freestyle.rubric]]
id = "observable-evidence"
criterion = "Observable deterministic behavior"
weight = 100
kind = "deterministic"
assessmentIds = {json.dumps(["builds", "runs"] + (["cold-launch"] if sid == "s09" else []))}
desc = "Every declared build and run scenario must pass."
''', encoding="utf-8")


def _state(root: Path, contract: dict) -> None:
    solved = [f"s{ordinal:02d}-l01-e01" for ordinal in range(1, 8)]
    state = {
        "v": 2, "booted": True, "credits": 0, "earned": 0,
        "hexesEnabled": False,
        "ex": {exercise_id: {"a": 1, "ok": True, "pts": 10, "hint": False, "reps": 1}
               for exercise_id in solved},
        "read": {f"s{ordinal:02d}-l01": True for ordinal in range(1, 8)},
        "fs": {f"s{ordinal:02d}": {"best": {
            "total": 100, "grade": "A", "essentialPassed": True,
            "independent": True, "at": 1,
        }} for ordinal in range(1, 8)},
        "inv": {"oracle": 0, "skip": 2, "firewall": 0, "x2": 0,
                "xray": 0, "vpn": 0},
        "oracleLog": [], "themes": {"vellum": True}, "theme": "vellum",
        "audio": {"ambience": False, "sfx": False, "volume": 0, "wind": 0,
                  "keys": {"profile": "quill", "vol": 0}, "ui": 0},
        "pen": {"trials": False, "drill": False},
        "ai": {"oracle": "", "oracleKind": "ollama", "grader": "",
               "graderKind": "claude-cli", "graderModel": "", "graderCommand": "",
               "keys": {"anthropic": "", "openai": ""}},
        "badges": {},
        "stats": {"correct": 7, "wrong": 0, "runs": 0, "subs": 0,
                  "streak": 0, "bestStreak": 0, "intrusionW": 0, "intrusionL": 0,
                  "atkW": 0, "atkL": 0, "atkWins": {}, "reviews": 0},
        "buffers": {}, "nav": {"view": "section", "sec": "s08", "lesson": None},
        "workspace": {"enabled": False, "dir": ""},
        "exerciseEvidence": {
            exercise_id: {"attempts": 1, "resolved": True, "supportUsed": False,
                          "supportKinds": [], "independent": False, "retained": False,
                          "capabilityIds": [contract["capabilityIds"][(index - 1)
                                                                      % len(contract["capabilityIds"])]],
                          "lastVariantId": ""}
            for index, exercise_id in enumerate(solved, 1)
        },
        "capabilityEvidence": {
            capability: {"taught": True, "practiced": False, "supported": False,
                         "independent": False, "retained": False, "due": False,
                         "evidenceIds": []}
            for capability in contract["capabilityIds"]
        },
        "masteryLabs": {}, "variantAssignments": {}, "assessmentReceipts": {},
        "masteryStatus": "learning",
    }
    save = root / "save"
    workspace = save / "workspace" / PROJECT
    workspace.mkdir(parents=True)
    (workspace / "main.py").write_text('print("READY")\n', encoding="utf-8")
    (save / "state.json").write_text(json.dumps(state, indent=2) + "\n", encoding="utf-8")


def _legacy_fixture(root: Path) -> None:
    (root / "tome.toml").write_text(f'''# Disposable legacy compatibility fixture.
[meta]
id = "{LEGACY_TOME_ID}"
name = "Legacy Browser Compatibility"
description = "Proves that non-evidence tomes retain legacy progression and copy."
author = "The Arcanum test harness"
version = "1.0.0"

[runtime]
name = "python"
project = "LegacyBrowser"
packages = false

[content]
sections = ["s01"]

[narrative]
objective = "Keep the classic chapter journey unchanged."
title = "ARCANUM // LEGACY COMPATIBILITY"
logo = "LEGACY JOURNEY"
opsLabel = "CHAPTERS"
graderPersona = "THE CLASSIC KEEPER"
studentTerm = "learner"
currency = "proof marks"
currencyShort = "pm"
gradeScale = "S|A|B|C|D|F"

[defaults]
theme = "vellum"

[economy]
ranks = [[0, "LEARNER"]]
''', encoding="utf-8")
    section = root / "sections" / "s01"
    (section / "lessons").mkdir(parents=True)
    (section / "section.toml").write_text('''id = "s01"
codename = "CHAPTER 1 // LEGACY"
short = "Legacy"
title = "Classic Progression"
build = "Keep the original completion threshold and grading path."
brief = "This chapter deliberately has no mastery evidence declaration."
''', encoding="utf-8")
    exercises = []
    for number in range(1, 11):
        exercises.append(f'''[[lessons.exercises]]
id = "s01-l01-e{number:02d}"
type = "mc"
points = 10
prompt = "Classic practice item {number}."
choices = ["Keep learning", "Erase compatibility"]
answer = 0
''')
    (section / "lessons" / "l01.toml").write_text('''[[lessons]]
id = "s01-l01"
title = "Classic Lesson"
body = """<p>Legacy tomes keep their original completion and grading semantics.</p>"""

''' + "\n".join(exercises), encoding="utf-8")
    (section / "freestyle.toml").write_text('''[freestyle]
title = "THE GREAT WORKING: LEGACY"
brief = "Keep the classic project path alive."
reward = 100
xray = "Classic private notes."

[freestyle.badge]
id = "badge-legacy"
name = "LEGACY"
desc = "Classic progression remains intact."

[[freestyle.rubric]]
criterion = "Classic behavior"
weight = 100
desc = "The legacy grader owns this path."
''', encoding="utf-8")
    save = root / "save"
    save.mkdir()
    state = {
        "v": 2, "booted": True, "credits": 0, "earned": 0,
        "hexesEnabled": False,
        "ex": {f"s01-l01-e{number:02d}": {
            "a": 1, "ok": True, "pts": 10, "hint": False, "reps": 0,
        } for number in range(1, 8)},
        "read": {"s01-l01": True}, "fs": {},
        "inv": {"oracle": 0, "skip": 0, "firewall": 0, "x2": 0,
                "xray": 0, "vpn": 0},
        "badges": {}, "stats": {}, "buffers": {},
        "nav": {"view": "section", "sec": "s01", "lesson": None},
        "workspace": {"enabled": False, "dir": ""},
    }
    (save / "state.json").write_text(json.dumps(state, indent=2) + "\n", encoding="utf-8")
    (root / MARKER).write_text("disposable browser fixture\n", encoding="utf-8")


def _install_legacy() -> None:
    stage = Path(tempfile.mkdtemp(prefix=f".{LEGACY_TOME_ID}-", dir=ROOT / "tomes"))
    try:
        _legacy_fixture(stage)
        stage.replace(LEGACY_TARGET)
        stage = Path()
    finally:
        if stage and stage.exists() and stage != Path("."):
            shutil.rmtree(stage)


def _install() -> None:
    _remove()
    stage = Path(tempfile.mkdtemp(prefix=f".{TOME_ID}-", dir=ROOT / "tomes"))
    try:
        contract, _sections = future_map(2)
        _manifest(stage)
        _section_files(stage, contract)
        write_working_assessments(stage)
        export_mastery_contract({"masteryEvidence": contract}, str(stage))
        generator = VariantGenerator(
            for_config({"name": "python"}), SemanticPass(), sandbox=PythonProofSandbox())
        for lab_path in write_labs(stage, contract):
            generator.generate(str(stage), str(lab_path))
        _state(stage, contract)
        (stage / MARKER).write_text("disposable browser fixture\n", encoding="utf-8")
        stage.replace(TARGET)
        stage = Path()
    finally:
        if stage and stage.exists() and stage != Path("."):
            shutil.rmtree(stage)
    try:
        _install_legacy()
    except Exception:
        _remove()
        raise


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("action", choices=("install", "remove"))
    args = parser.parse_args()
    if args.action == "install":
        _install()
        print(TARGET)
    else:
        _remove()
        print(f"removed {TARGET}")


if __name__ == "__main__":
    main()
