"""Language-neutral runtime operation protocol consumed by application services."""
from __future__ import annotations

from typing import Protocol


class Runtime(Protocol):
    NAME: str
    LANGUAGE: str
    VERSION: int
    CAPABILITIES: tuple[str, ...]

    def available(self) -> bool: ...
    def scaffold(self, project_dir: str, project_name: str) -> str: ...
    def seed_workspace(self, project_dir: str, project_name: str, *, force: bool = False,
                       only_missing: bool = False) -> dict: ...
    def collect_code(self, project_dir: str) -> list[tuple[str, str]]: ...
    def project_file(self, project_name: str) -> str: ...
    def run_project(self, project_dir: str, stdin_text: str, args=(), env=None,
                    timeout=None) -> dict: ...
    def build_diagnostics(self, project_dir: str) -> dict: ...
    def run_snippet(self, scratch_base: str, code: str, stdin_text: str,
                    env=None) -> dict: ...
    def snippet_diagnostics(self, scratch_base: str, code: str, env=None) -> dict: ...
    def add_package(self, project_dir: str, package: str) -> dict: ...
