import assert from "node:assert/strict";
import fs from "node:fs";

const setup = fs.readFileSync("web/app/forge/forge.js", "utf8");
const session = fs.readFileSync("web/app/forge/bindery.js", "utf8");
const traceLines = fs.readFileSync("web/app/forge/trace-lines.js", "utf8");
const binder = fs.readFileSync("web/app/forge/binder.js", "utf8");
const baseCss = fs.readFileSync("web/css/overlay/bindery/base.css", "utf8");
const resetCss = fs.readFileSync("web/css/overlay/bindery/binder-reset.css", "utf8");
const sessionCss = fs.readFileSync("web/css/overlay/bindery/session.css", "utf8");
const launcher = fs.readFileSync("start.sh", "utf8");
const main = fs.readFileSync("web/app/main.js", "utf8");
const phaseMatch = session.match(/export const FORGE_PHASES = \[([\s\S]*?)\];/);
assert.ok(phaseMatch);
assert.equal((phaseMatch[1].match(/"[^"]+"/g) || []).length, 8);
assert.match(setup, /THE AUTHOR/);
assert.match(setup, /aria-label="Author agent CLI"/);
assert.match(setup, /aria-label="Author model"/);
assert.match(setup, /aria-label="Author effort"/);
assert.match(setup, /THOROUGH REVIEWER AI/);
assert.match(setup, /reads every authored[\s\S]*no sampling/i);
assert.match(setup, /aria-label="About thorough reviewer AI"/);
assert.doesNotMatch(setup, /class="forge-reviewer-copy"/);
assert.match(setup, /forge-reviewer-field[\s\S]*forge-reviewer-head[\s\S]*THOROUGH REVIEWER AI[\s\S]*About thorough reviewer AI[\s\S]*forge-reviewer-toggle[\s\S]*fg-review-enabled[\s\S]*ENABLE \(OPTIONAL\)/);
assert.match(setup, /aria-label="Reviewer agent CLI"/);
assert.match(setup, /reviewer, bindery: \{ author, reviewer \}/);
assert.match(setup, /RESUME FROM CURRENT/);
assert.match(setup, /RESTART FROM PHASE/);
assert.match(setup, /id="fg-resume-ack"/);
assert.match(setup, /confirm: "reset-tome-build"/);
assert.match(setup, /fromPhase: restartPhase/);
assert.match(setup, /\/api\/buildtome\/reset/);
assert.doesNotMatch(setup, /THE DRAFTER|THE REVIEWER|quality|advised/);
assert.match(session, /AUTHOR TOOL HISTORY/);
assert.match(session, /id="tome-forge" disabled aria-busy="true"/);
assert.match(session, /fetchActiveBuilds\(\{ failClosed: true \}\)/);
assert.match(session, /forgeButton\.disabled = busy/);
assert.match(session, /setTimeout\(refreshActiveBuilds, 3000\)/);
assert.match(session, /Finish or abandon the current working/);
assert.match(session, /fetch\(`\/api\/buildtome\/status\?id=/);
assert.match(session, /data-trace="\$\{esc\(build\.traceId \|\| build\.id\)\}"/);
assert.match(session, /openBuildOverlay\(button\.dataset\.job, button\.dataset\.trace\)/);
assert.match(session, /\/api\/buildtome\/pause/);
assert.match(session, /\/api\/buildtome\/message/);
assert.match(session, /\/api\/buildtome\/continue/);
assert.match(session, /mergeForgeTraceLines\(tooling\?\.lines, status\.logtail, traceAnchor\)/);
assert.match(traceLines, /VALIDATOR COMMAND \(\?:START\|COMPLETE\|FAILED\)/);
assert.match(traceLines, /rows\.sort/);
assert.match(session, /class="forge-chat-text"/);
assert.match(session, /function messageStamp\(value\)/);
assert.doesNotMatch(session, /function commandStamp\(line\)/);
assert.doesNotMatch(session, /forge-terminal-time|forge-terminal-command/);
assert.match(session, /<div class="forge-terminal-line">\$\{esc\(line\)\}<\/div>/);
assert.match(session, /<time datetime=/);
assert.match(session, /forge-console-actions[\s\S]*id="fp-pause"[\s\S]*id="fp-send"/);
assert.doesNotMatch(session, /forge-session-actions[\s\S]{0,300}id="fp-pause"/);
assert.match(session, /pauseTransition === "pause" \? "pausing"/);
assert.match(session, /pause\.disabled = state === "pausing" \|\| state === "resuming"/);
assert.doesNotMatch(session, /setTimeout\(\(\) => \{ pause\.disabled = false/);
assert.match(session, /phaseLine\(status, state\)/);
assert.match(session, /active && status\.phaseStartedAt/);
assert.match(session, /phase\.dataset\.state = state/);
assert.match(session, /id="fp-model">ATTACHING/);
assert.match(session, /status\.sessionAuthor \|\| \{\}/);
assert.match(session, /author\.model/);
assert.match(baseCss, /#fp-phase\[data-state="pausing"\]/);
assert.match(baseCss, /\.forge-depth input\[type="range"\]\s*\{[^}]*min-width:\s*0/s);
assert.match(sessionCss, /\.forge-dials \.forge-field,[\s\S]*?\.forge-dials \.forge-depth\s*\{[^}]*min-width:\s*0/s);
assert.match(baseCss, /\.forge-ai-row\s*\{[^}]*display:\s*grid[^}]*grid-template-columns:/s);
assert.match(sessionCss, /\.tome-row\.forge:disabled\s*\{[^}]*filter:\s*grayscale\(\.82\)[^}]*opacity:\s*\.56/s);
assert.match(sessionCss, /\.forge-author-field\s*\{[^}]*padding:[^}]*border:/s);
assert.match(sessionCss, /\.forge-reviewer-field\s*\{[^}]*border:[^}]*background:/s);
assert.match(sessionCss, /\.forge-reviewer-options\s*\{[^}]*margin-top:\s*2px/s);
assert.doesNotMatch(sessionCss, /\.forge-reviewer-options\s*\{[^}]*margin-left:/s);
assert.doesNotMatch(sessionCss, /\.forge-terminal-line\s*\{[^}]*grid-template-columns:/s);
assert.match(sessionCss, /\.forge-resume-field\s*\{[^}]*border:[^}]*background:/s);
assert.match(sessionCss, /\.forge-field \.forge-resume-ack\s*\{[^}]*color:\s*var\(--bad\)/s);
assert.match(sessionCss, /\.forge-session-model strong\s*\{[^}]*color:\s*var\(--ac\)/s);
assert.match(sessionCss, /\.forge-composer textarea\s*\{[^}]*resize:\s*none/s);
assert.match(sessionCss, /--forge-body-size:\s*12\.5px/);
assert.match(sessionCss, /--forge-meta-size:\s*9\.5px/);
assert.match(sessionCss, /\.forge-composer textarea\s*\{[^}]*font:\s*var\(--forge-body-size\)[^}]*var\(--fell\)/s);
assert.match(sessionCss, /\.forge-composer textarea::placeholder\s*\{[^}]*font:\s*inherit/s);
assert.match(sessionCss, /\.forge-chat-text\s*\{[^}]*white-space:\s*pre-wrap/s);
assert.match(sessionCss, /\.forge-chat-meta\s*\{[^}]*justify-content:\s*space-between/s);
assert.doesNotMatch(sessionCss, /\.forge-chat\s*\{[^}]*white-space:\s*pre-wrap/s);
assert.match(sessionCss, /\.forge-console-btn\s*\{[^}]*background:[^}]*color:/s);
assert.match(sessionCss, /\.forge-console-btn\s*\{[^}]*min-height:\s*26px[^}]*font:\s*10\.5px/s);
const resetOptions = binder.match(/<select id="bd-phase"[\s\S]*?<\/select>/)?.[0] || "";
assert.equal((resetOptions.match(/<option value="[1-8]">/g) || []).length, 8);
assert.match(binder, /Every authored section is replaced by fresh Phase 3 placeholders/);
assert.match(binder, /prepareStateReset\(\)/);
assert.match(binder, /confirm: "reset-tome-build"/);
assert.match(binder, /\/api\/buildtome\/reset/);
assert.match(binder, /\/api\/buildtome\/resume/);
assert.match(resetCss, /\.binder-rebuild-consequence\s*\{[^}]*border-left:\s*2px solid var\(--bad\)/s);
assert.match(main, /openResetBuildJob/);
assert.match(main, /openBuildOverlay\(resetBuildJob\)/);
assert.match(launcher, /\/api\/buildtome\/active/);
assert.match(launcher, /active author session/);
assert.match(launcher, /if \[\[ "\$active_jobs" =~ \^\[1-9\]/);
assert.match(main, /#term, \.forge-log, \.forge-workbench/);
console.log("single-author forge UI: OK");
